spring:
  datasource:
    url: jdbc:mysql://39.105.211.35:3307/shasly
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 39.105.211.35
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 20
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 2
      #最大阻塞时等待时间
      max-wait: 3000
      #链接超时时间
      timeout: 2000

#配置分页
pagehelper:
  helper-dialect: mysql
  params: count=countsql
  reasonable: true
  support-methods-arguments: true
